repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: make pylint
        language: system
        types: [python]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.960
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies: [types-requests==2.27.30, types-geoip2==3.0.0]
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
