language: python

addons:
  apt:
    packages:
    - python-systemd
    - python3-systemd

python:
  - "2.7"
  - "3.3"
  - "3.4"

install:
  - "pip install pylint==1.3.1 pytest mock pep8 kafka-python coverage coveralls"
  - "pip install https://github.com/systemd/python-systemd/zipball/master"

script:
  - "(python -V 2>&1 | grep -qF 'Python 2.6') || make pylint"
  - "make pep8"

sudo: false

after_success:
  - coveralls
