language: python
dist: trusty

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libsystemd-journal-dev libsystemd-daemon-dev libsystemd-login-dev"

python:
  - "3.4"

install:
  - "pip install pylint pytest mock pep8 kafka-python coverage coveralls"
  - "pip install https://github.com/systemd/python-systemd/zipball/master"

script:
  - "make pylint"
  - "make pep8"

sudo: required

after_success:
  - coveralls
