language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"


before_install:
  - "sudo apt-get install -y libsystemd-journal-dev"

install:
  - "pip install pylint==1.3.1 pytest mock pep8 kafka-python coverage coveralls"
  - "pip install https://github.com/systemd/python-systemd/zipball/master"

script:
  - "(python -V 2>&1 | grep -qF 'Python 2.6') || make pylint"
  - "make pep8"

sudo: true

after_success:
  - coveralls
