language: python
dist: xenial

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libsystemd-dev"

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - "pip install pylint pytest mock flake8 kafka-python coverage coveralls requests responses boto3"
  - "pip install https://github.com/systemd/python-systemd/zipball/master"

script:
  - "make flake8"
  - "make pylint"
  - "make unittest"

sudo: required

after_success:
  - coveralls
