language: python
dist: trusty

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install -y libsystemd-journal-dev libsystemd-daemon-dev libsystemd-login-dev"

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - "pip install pylint pytest mock flake8 kafka-python coverage coveralls requests"
  - "pip install https://github.com/systemd/python-systemd/zipball/master"

script:
  - "make flake8"
  - "make pylint"
  - "make unittest"

sudo: required

after_success:
  - coveralls
