[mypy]
python_version = 3.10
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
disallow_untyped_calls = True
warn_unused_ignores = True
disallow_any_generics = True

[mypy-botocore,botocore.*,googleapiclient,googleapiclient.*,kafka,kafka.*,re2,snappy,systemd,systemd.*,zstandard]
ignore_missing_imports = True
