[mypy]
python_version = 3.10
ignore_missing_imports = True
check_untyped_defs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True

[mypy-generate_logs]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.daemon]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.journalpump]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.rsyslog]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.aws_cloudwatch]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.base]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.elasticsearch_opensearch_sender]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.file]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.google_cloud_logging]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.kafka_sender]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.logplex]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.rsyslog]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.senders.websocket]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.statsd]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-journalpump.util]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-systest.test_rotation]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-systest.test_rsyslog]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-systest.util]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.test_elasticsearch_opensearch_sender]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.test_google_cloud_logging]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.test_journalpump]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.test_rsyslog]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.test_websocket]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.unit.senders.test_base]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.unit.senders.test_kafka_sender]
disallow_untyped_defs = False
disallow_incomplete_defs = False

[mypy-test.unit.senders.test_rsyslog_sender]
disallow_untyped_defs = False
disallow_incomplete_defs = False
