name: Build journalpump

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only use oldest and newest version for the lint step
        python-version: ["3.9", "3.11"]

    steps:

      - id: checkout-code
        uses: actions/checkout@v2

      - id: system-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev libsnappy-dev

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: python-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - id: pre-commit
        run: pre-commit run --all

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.11"]

    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: system-dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev libsnappy-dev

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: python-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade -r requirements.dev.txt
          pip install -e .

      - id: unittest
        run: make coverage

      - id: systest
        run: make systest

      - id: upload-codecov
        # Third-party action pinned to v2.1.0
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
        with:
          verbose: true
