name: Build journalpump

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # only use one version for the lint step
        python-version: [3.9]

    steps:

      - id: checkout-code
        uses: actions/checkout@v2

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsystemd-dev
          pip install -r requirements.txt
          pip install -r requirements.dev.txt

      - id: pylint
        run: |
          make lint

      - id: typecheck
        run: |
          make typecheck

      - id: validate-style
        run: |
          make fmt
          if [ $(git diff --name-only --diff-filter=ACMR | wc -l ) != 0 ]; then
            echo "Reformatting failed! Please run make fmt on your commits and resubmit!" 1>&2;
            git diff;
            exit 1;
          fi

  test:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - id: checkout-code
        uses: actions/checkout@v2

      - id: prepare-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - id: dependencies
        run: |
          sudo apt-get update
          # Setup build deps
          sudo apt-get install -y libsystemd-dev
          # Setup common python dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade -r requirements.dev.txt
          pip install -e .

      - id: unittest
        run: make unittest

      - id: systest
        run: make systest
